---
title: "Supplemental Appendix in support of PAPER TITLE"
author: "Subodh Adhikari, Sanford Eigenbrode, Erich Seamon"
date: "10/22/2021"
fontsize: 12pt
output:
  pdf_document:
    toc: yes
    toc_depth: 2
    fig_caption: yes
    number_sections: no
  linestretch: 1.5
  header-includes:
    \usepackage{pdflscape}
    \newcommand{\blandscape}{\begin{landscape}}
    \newcommand{\elandscape}{\end{landscape}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/mnt/ceph/erichs/git/aphids/supplemental_appendix/")  # with something else than `getwd()`
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#aphid_modeling.R

#i options:

#TotAph
#Mfc
#TotAphNoMfc
#RelAbundMfc
#TotDn
#Totsg
#TotRp
#TotSa
#TotMd
#TotRm
#TotMfc
#TotSe
#TotAm
#TotRi

aphid_model <- function(i) {

library(dplyr)
library(lubridate)
library(tidyr)
library(data.table)
library(caret)
library(doParallel)
library(plyr)
library(gridExtra)
library(rattle)
library(rpart)


library(cluster)
library(factoextra)

options(scipen = 999)

data <- read.csv("./data/Aphid_data_Wide_RAW.csv")

data2 <- read.csv("./data/Aphid_wide_Allrings_5.9.21.csv")

data3 <- read.csv("./data/aphid_data_long.csv")

data4 <- read.csv("./data/aphid_data_wide.csv")


data2 <- data2[,-c(3,6,8,9)]


#π(R + r) (R - r) - ring area

data2$area <- (pi*(data2$ringfinal/2) + ((data2$ringfinal/2) - 250)) * ((data2$ringfinal/2) - ((data2$ringfinal/2) - 250))

data2$Spring.Wheat_area <- data2$Spring.Wheat * data2$area
data2$Winter.Wheat_area <- data2$Winter.Wheat * data2$area
data2$allwheat_area <- data2$allwheat * data2$area
data2$Fallow_area <- data2$Fallow * data2$area
data2$AllCereal_area <- data2$AllCereal * data2$area
data2$AllGrasslands_area <- data2$AllGrasslands * data2$area
data2$AllLegumes_area <- data2$AllLegumes * data2$area

data2WW <- aggregate(data2$Winter.Wheat_area, by=list(data2$site_year), FUN = 'sum')
data2WW$Winter.Wheat_pct <- data2WW$x/12566370
data2SW <- aggregate(data2$Spring.Wheat_area, by=list(data2$site_year), FUN = 'sum')
data2SW$Spring.Wheat_pct <- data2SW$x/12566370
data2AW <- aggregate(data2$allwheat_area, by=list(data2$site_year), FUN = 'sum')
data2AW$allwheat_pct <- data2AW$x/12566370
data2F <- aggregate(data2$Fallow_area, by=list(data2$site_year), FUN = 'sum')
data2F$Fallow_pct <- data2F$x/12566370
data2AC <- aggregate(data2$AllCereal_area, by=list(data2$site_year), FUN = 'sum')
data2AC$AllCereal_pct <- data2AC$x/12566370
data2AG <- aggregate(data2$AllGrasslands_area, by=list(data2$site_year), FUN = 'sum')
data2AG$AllGrasslands_pct <- data2AG$x/12566370
data2AL <- aggregate(data2$AllLegumes_area, by=list(data2$site_year), FUN = 'sum')
data2AL$AllLegumes_pct <- data2AL$x/12566370

data2a <- cbind(data2WW[c(1,3)], data2SW[3], data2AW[3], data2AC[3], data2AG[3], data2AL[3])

data2 <- subset(data2, ringfinal == 4000)
data2 <- merge(data2, data2a, by.x = "site_year", by.y = "Group.1")


#write.csv(data2, "/mnt/ceph/erichs/git/aphids/modeldata/Aphid_data_combined_092121.csv")


set.seed(103)

fits<-list()
fits_summary <- NULL

#dependent <- colnames(data2[c(32,22,20,23)])
fmla <- as.formula(paste(colnames(data2[i]), " ~ ", paste(colnames(data2[c(44,45,46,47,48,49,15,3,4)]), collapse= "+")))

#corrplot(cor(data2a[c(20,8,9,10,11,3,4)]), method = "square")
# 
# data2[i] <- log10(data2[i])
# data2 <- data2[!is.infinite(eval(parse(text=paste("data2$", colnames(data2[i]), sep="")))),]

inTraining <- createDataPartition(eval(parse(text=paste("data2$", colnames(data2[i]), sep=""))), p = .7, list = FALSE)
training <- data2[ inTraining,]
testing  <- data2[-inTraining,]

train_control<- trainControl(method="repeatedcv", savePredictions = "final", returnResamp='all')

fit_rf <- caret::train(fmla, data=training, method="rf", trControl = train_control)
# fit_glm <- caret::train(fmla, data=training, method="glm", trControl = train_control)
# fit_knn <- caret::train(fmla, data=training, method="knn",trControl = train_control)
# fit_svm <- caret::train(fmla, data=training, method="svmRadial", trControl = train_control)
# fit_treebag <- caret::train(fmla, data=training, method="treebag", trControl = train_control)
# fit_gbm <- caret::train(fmla, data=training, method="gbm", trControl = train_control)

fit_rpart <- caret::train(fmla, data=training, method="rpart", trControl = train_control)


# 
#data.fit1 <- randomForest(TotMfc ~ Fallow + AllCereal + AllGrasslands + AllLegumes + CDD + LULCRich + CP + ringfinal, data = training, importance = TRUE, na.action = na.omit, mtry = 3)
# data.fit2 <- randomForest(TotAphNoMfc ~ Fallow + AllCereal + AllGrasslands + AllLegumes + CDD + LULCRich + CP + ringfinal, data = training, importance = TRUE, na.action = na.omit, mtry = 3)
# data.fit3 <- randomForest(TotAph ~ Fallow + AllCereal + AllGrasslands + AllLegumes  + CDD + LULCRich + CP + ringfinal, data = training, importance = TRUE, na.action = na.omit, mtry = 3)
# data.fit4 <- randomForest(RelAbundMfc ~ Fallow + AllCereal + AllGrasslands + AllLegumes  + CDD + LULCRich + CP + ringfinal, data = training, importance = TRUE, na.action = na.omit, mtry = 3)

#---Learning Curve Analysis


tree_num <- which(fit_rf$finalModel$err.rate[, 1] == min(fit_rf$finalModel$err.rate[, 1]))

lda_data <- learning_curve_dat(dat = fit_rf$trainingData,
                               outcome = ".outcome",
                               ## `train` arguments:
                               metric = "RMSE",
                               trControl = train_control,
                               method = "rf", verbose = FALSE)

pts <- pretty(lda_data$RMSE)
#pts <- c(0,0.1, 0.2, 0.3, 0.4)

lda_data$Data[lda_data$Data == "Resampling"] <- c("Validation")
p1 <- ggplot(lda_data, aes(x = Training_Size, y = RMSE, color = Data)) +
  
  geom_smooth(method = loess, span = .8) +
  theme_bw()  + ggtitle("Learning Curve Analysis") + theme(axis.title.y = element_text(size=10), axis.title.x = element_text(size = 10), axis.text.x = element_text(size=rel(1), angle = 90, hjust = 1), axis.text.y = element_text(size=rel(1), hjust = 1)) + theme(plot.title = element_text(vjust = 2))  + theme(legend.text=element_text(size=10)) + theme(legend.title=element_text(size=14, face = "bold")) + theme(plot.title = element_text(size=14, face = "bold")) + scale_y_continuous(labels = pts, breaks = pts ) + xlab("Training Size") + ylab("RMSE") + theme(legend.position="bottom") + scale_fill_discrete(name = "Legend")



p2 <- ggplot(varImp(fit_rf)) + theme_bw()

grid.arrange(p1,p2, ncol = 2)
print(fit_rf)

#fancyRpartPlot(fit_rpart$finalModel, caption = NULL)


assign(paste("importance_", i, sep=""), varImp(fit_rf))

}

```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#aphid_modeling.R

#i options:

#TotAph
#Mfc
#TotAphNoMfc
#RelAbundMfc
#TotDn
#Totsg
#TotRp
#TotSa
#TotMd
#TotRm
#TotMfc
#TotSe
#TotAm
#TotRi

aphid_model_data <- function(i) {

library(dplyr)
library(lubridate)
library(tidyr)
library(data.table)
library(caret)
library(doParallel)
library(plyr)
library(gridExtra)
library(rattle)
library(rpart)


library(cluster)
library(factoextra)

options(scipen = 999)

data <- read.csv("./data/Aphid_data_Wide_RAW.csv")

data2 <- read.csv("./data/Aphid_wide_Allrings_5.9.21.csv")

data3 <- read.csv("./data/aphid_data_long.csv")

data4 <- read.csv("./data/aphid_data_wide.csv")


unique_ids <- subset(data2, ringfinal == 4000)
points(x=unique_ids$Lat,y=unique_ids$Long,col='red',cex=0.75)

base_world <- map_data("world")

map_data <- 
  base_world +
  geom_point(data=unique_ids, 
             aes(x=Long, y=Lat), colour="Deep Pink", 
             fill="Pink",pch=21, size=5, alpha=I(0.7))

map_data


data2 <- data2[,-c(3,6,8,9)]


#π(R + r) (R - r) - ring area

data2$area <- (pi*(data2$ringfinal/2) + ((data2$ringfinal/2) - 250)) * ((data2$ringfinal/2) - ((data2$ringfinal/2) - 250))

data2$Spring.Wheat_area <- data2$Spring.Wheat * data2$area
data2$Winter.Wheat_area <- data2$Winter.Wheat * data2$area
data2$allwheat_area <- data2$allwheat * data2$area
data2$Fallow_area <- data2$Fallow * data2$area
data2$AllCereal_area <- data2$AllCereal * data2$area
data2$AllGrasslands_area <- data2$AllGrasslands * data2$area
data2$AllLegumes_area <- data2$AllLegumes * data2$area

data2WW <- aggregate(data2$Winter.Wheat_area, by=list(data2$site_year), FUN = 'sum')
data2WW$Winter.Wheat_pct <- data2WW$x/12566370
data2SW <- aggregate(data2$Spring.Wheat_area, by=list(data2$site_year), FUN = 'sum')
data2SW$Spring.Wheat_pct <- data2SW$x/12566370
data2AW <- aggregate(data2$allwheat_area, by=list(data2$site_year), FUN = 'sum')
data2AW$allwheat_pct <- data2AW$x/12566370
data2F <- aggregate(data2$Fallow_area, by=list(data2$site_year), FUN = 'sum')
data2F$Fallow_pct <- data2F$x/12566370
data2AC <- aggregate(data2$AllCereal_area, by=list(data2$site_year), FUN = 'sum')
data2AC$AllCereal_pct <- data2AC$x/12566370
data2AG <- aggregate(data2$AllGrasslands_area, by=list(data2$site_year), FUN = 'sum')
data2AG$AllGrasslands_pct <- data2AG$x/12566370
data2AL <- aggregate(data2$AllLegumes_area, by=list(data2$site_year), FUN = 'sum')
data2AL$AllLegumes_pct <- data2AL$x/12566370

data2a <- cbind(data2WW[c(1,3)], data2SW[3], data2AW[3], data2AC[3], data2AG[3], data2AL[3])

data2 <- subset(data2, ringfinal == 4000)
data2 <- merge(data2, data2a, by.x = "site_year", by.y = "Group.1")


#write.csv(data2, "/mnt/ceph/erichs/git/aphids/modeldata/Aphid_data_combined_092121.csv")

}

```


## Total Aphids Model

```{r, warning=FALSE, message=FALSE, echo=FALSE}
model_TotAph <- aphid_model("TotAph")
```
\newpage

## Total Aphids No Mfc Model

```{r, warning=FALSE, message=FALSE, echo=FALSE}
model_TotAphNoMfc <- aphid_model("TotAphNoMfc")
```
\newpage

## Relative Abundance Mfc Model

```{r, warning=FALSE, message=FALSE, echo=FALSE}
model_RelAbundMfc <- aphid_model("RelAbundMfc")
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#aphid_model("TotDn")
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#aphid_model("Totsg")
```
\newpage

## Individual Aphids: Rp

```{r, warning=FALSE, message=FALSE, echo=FALSE}
model_TotRp <- aphid_model("TotRp")
```
\newpage

## Individual Aphids: Sa

```{r, warning=FALSE, message=FALSE, echo=FALSE}
model_TotSa <- aphid_model("TotSa")
```
\newpage

## Individual Aphids: Md

```{r, warning=FALSE, message=FALSE, echo=FALSE}
model_TotMd <- aphid_model("TotMd")
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#aphid_model("TotRm")
```
\newpage

## Individual Aphids: Mfc

```{r, warning=FALSE, message=FALSE, echo=FALSE}
model_TotMfc <- aphid_model("TotMfc")
```
\newpage

<!-- ## Individual Aphids: Rp -->

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#model_TotSe <- aphid_model("TotSe")
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#aphid_model("TotAm")
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#aphid_model("TotRi")
```
\newpage

```{r, warning=FALSE, message=FALSE, echo=FALSE}
# 
# fit <- varImp(fit_rf)
# fit$importance$type <- i
# 
# fit$importance$name <- rownames(fit$importance)
# 
# fit_summary <- max(fit_rf$finalModel[5]$rsq)
# fits_summary[[i]] <- fit_summary
# 
# fits[[i]] <- fit$importance

```
  
  
```{r, warning=FALSE, message=FALSE, echo=FALSE}

models <- cbind(model_TotAph$importance,model_TotAphNoMfc$importance,model_RelAbundMfc$importance,model_TotRp$importance,model_TotSa$importance,model_TotMd$importance,model_TotMfc$importance)

colnames(models) <- c("TotAph", "TotAphNoMfc", "RelAbundMfc", "TotRp", "TotSa", "TotMd", "TotMfc")
rownames(models) <- c("Winter Wheat", "Spring Wheat", "All Wheat", "All Cereals", "All Grasslands", "All Legumes", "LULCeven", "Cumulative Degree Days", "Cumulative Precip" )
models <- t(models)

models2 <- melt(models)
models2 <- as.data.frame(models2)

model_aph <- subset(models2, Var1 == "TotAph" | Var1 == "TotAphNoMfc" | Var1 == "RelAbundMfc")
model_other <- subset(models2, Var1 == "TotRp" | Var1 == "TotSa" | Var1 == "TotMd" | Var1 == "TotMfc" )
model_other_refined <- subset(model_other, Var2 == "")

ggplot(model_aph, aes(x = Var2,  y = value, group = Var1, colour = Var1)) +
  geom_line(aes(color = Var1)) + theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) + xlab("Cropping systems and Climate") +
  ylab("Feature Importance") +
  ggtitle("Feature Importance Comparison: Total Aphids vs. Mfc") +
scale_colour_discrete(name="Aphid Types")

ggplot(model_other, aes(x = Var2,  y = value, group = Var1, colour = Var1)) +
  geom_line(aes(color = Var1)) + theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) + xlab("Cropping systems and Climate") +
  ylab("Feature Importance") +
  ggtitle("Feature Importance Comparison: Other Aphids") +
scale_colour_discrete(name="Aphid Types")


```

```{r, warning=FALSE, message=FALSE, echo=FALSE}

models <- cbind(model_TotAph$importance,model_TotAphNoMfc$importance,model_RelAbundMfc$importance,model_TotRp$importance,model_TotSa$importance,model_TotMd$importance,model_TotMfc$importance)

colnames(models) <- c("TotAph", "TotAphNoMfc", "RelAbundMfc", "TotRp", "TotSa", "TotMd", "TotMfc")
rownames(models) <- c("Winter Wheat", "Spring Wheat", "All Wheat", "All Cereals", "All Grasslands", "All Legumes", "LULCeven", "Cumulative Degree Days", "Cumulative Precip" )
models <- t(models)

models2 <- melt(models)
models2 <- as.data.frame(models2)

model_aph <- subset(models2, Var1 == "TotAph" | Var1 == "TotAphNoMfc" | Var1 == "RelAbundMfc")
model_other <- subset(models2, Var1 == "TotSa" | Var1 == "TotMd" | Var1 == "TotMfc" )
model_other_refined <- subset(model_other, Var2 == "")
# 
 # ggplot(model_aph, aes(x = Var2,  y = value, group = Var1, colour = Var1)) +
 # geom_line(aes(color = Var1)) + theme_bw() +
 #   theme(axis.text.x = element_text(angle = 90)) + xlab("Cropping systems and Climate") +
 #   ylab("Feature Importance") +
 #   ggtitle("Feature Importance Comparison: Total Aphids vs. Mfc") +
 # scale_colour_discrete(name="Aphid Types")

model_other <- subset(model_other, Var2 == "Cumulative Degree Days" | Var2 == "Cumulative Precip" | Var2 == "All Wheat" | Var2 == "LULCeven")
model_other$Var2 <- factor(model_other$Var2)

model_other <- model_other[c(10,11,12,7,8,9,4,5,6,1,2,3),]
model_other <- model_other[order(model_other$Var2), ]
model_other$Var2 <- factor(model_other$Var2, levels=rev(levels(model_other$Var2)))


levels(model_other$Var2) <- c("Cumulative Precipitation","Cumulative Degree Days","Landscape Diversity", "Proportion of Wheat")
levels(model_other$Var1) <- c("TotAph","TotAphNoMfc","RelAbundMfc", "TotRp", "S. avenae", "M. dirhodum", "M.f. cerealium")

colnames(model_other) <- c("Legend", "Var2", "value")
ggplot(model_other, aes(x = Var2,  y = value, group = Legend, fill = Legend)) +
    geom_bar(width=0.7,  position=position_dodge(width=0.75), stat="identity") + #geom_line(aes(color = Var1)) + theme_bw() +
  theme(axis.text.x = element_text(angle = 0)) + xlab("Variables") +
  ylab("Feature Importance Value") +
scale_colour_discrete(name="Aphid Types") + theme_minimal()


```





```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(ggplot2)

# data_totaph <- aphid_model_data("TotAph")

aez_sites <- read.csv("../supplemental_appendix/data/AEZ_sites.csv")
# 
# library(maptools
#   AEZ <- readShapePoly('../supplemental_appendix/data/AEZ_basic.shp',
#                           proj4string=CRS
#                           ("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
#   projection = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")

aez_sites$gridname <- as.factor(aez_sites$gridcode)
levels(aez_sites$gridname) <- c("Annual Crop", "Crop-Fallow Transition", "Crop-Fallow", "Irrigated")


  ggplot(aez_sites, aes(x=gridcode)) + geom_histogram(fill="gray", position="dodge") + theme_classic() + labs(x = "Agroecozone", y = "Number of Aphid Collection Sites") +stat_count(aes(y=..count..,label=..count..),geom="text",hjust=-.1,  vjust=-.50) + ggtitle("Biotic Collection Sites by Agroecological Zone")+ coord_flip()
  # + scale_x_discrete(labels= aez_sites$gridname)
  
  # 
  # 
  # +
  # geom_text(aes(label = Frequency,y=Pos), size = 3) 
  # 
  
  
  
  
  
  
  
  

```

